const options = [
    {
        bg: 'bg-[#3A4663]',
        innerBgScreen: 'bg-[#181F33]',
        innerBgCalculator: 'bg-[#242D44]',
        numberColor: 'text-[#FFF]',
        buttonNumColor: 'text-[#434A59]',
        buttonBg: 'bg-[#EAE3DC]',
        toggleBg: 'bg-[#242D44]',
        deleteresetBg: 'bg-[#647198]',
        equalBg: 'bg-[#D03F2F]',
        shadowNumbers: 'shadow-firstTheme-inset',
        shadowDeleteReset: 'shadow-firstTheme-deleteresetinset',
        equalShadow: 'shadow-firstTheme-equalinset',
        equalColor: 'text-white',
        hoverNumberColor: 'sm:active:bg-[#FFFFFE]',
        hoverDeleteResetColor: 'sm:active:bg-[#A2B2E1]',
        hoverEqualColor: 'sm:active:bg-[#F96B5B]',
    },
    {
        bg: 'bg-[#E6E6E6]',
        innerBgScreen: 'bg-[#EEE]',
        innerBgCalculator: 'bg-[#D2CDCD]',
        numberColor: 'text-[#36362C]',
        buttonNumColor: 'text-[#36362C]',
        buttonBg: 'bg-[#E5E4E1]',
        toggleBg: 'bg-[#242D44]',
        deleteresetBg: 'bg-[#378187]',
        equalBg: 'bg-[#C85402]',
        shadowNumbers: 'shadow-secondTheme-inset',
        shadowDeleteReset: 'shadow-secondTheme-deleteresetinset',
        equalShadow: 'shadow-secondTheme-equalinset',
        equalColor: 'text-white',
        hoverNumberColor: 'sm:active:bg-[#FFF]',
        hoverDeleteResetColor: 'sm:active:bg-[#62B5BC]',
        hoverEqualColor: 'sm:active:bg-[#FF8A38]',
    },
    {
        bg: 'bg-[#17062A]',
        innerBgScreen: 'bg-[#1E0936]',
        innerBgCalculator: 'bg-[#1E0936]',
        numberColor: 'text-[#FFE53D]',
        buttonNumColor: 'text-[#FFE53D]',
        buttonBg: 'bg-[#331C4D]',
        toggleBg: 'bg-[#1E0936]',
        deleteresetBg: 'bg-[#56077C]',
        equalBg: 'bg-[#00DED0]',
        shadowNumbers: 'shadow-thirdTheme-inset',
        shadowDeleteReset: 'shadow-thirdTheme-deleteresetinset',
        equalShadow: 'shadow-thirdTheme-equalinset',
        equalColor: 'text-black',
        hoverNumberColor: 'sm:active:bg-[#6C34AC]',
        hoverDeleteResetColor: 'sm:active:bg-[#8631AF]',
        hoverEqualColor: 'sm:active:bg-[#93FFF8]',
    },
];

export default options;
